#### 문제 설명
#### 두 개의 단어 begin, target과 단어의 집합 words가 있습니다. 아래와 같은 규칙을 이용하여 begin에서 target으로 변환하는 가장 짧은 변환 과정을 찾으려고 합니다.
#### 
#### 1. 한 번에 한 개의 알파벳만 바꿀 수 있습니다.
#### 2. words에 있는 단어로만 변환할 수 있습니다.
#### 예를 들어 begin이 "hit", target가 "cog", words가 ["hot","dot","dog","lot","log","cog"]라면 "hit" -> "hot" -> "dot" -> "dog" -> "cog"와 같이 4단계를 거쳐 변환할 수 있습니다.
#### 
#### 두 개의 단어 begin, target과 단어의 집합 words가 매개변수로 주어질 때, 최소 몇 단계의 과정을 거쳐 begin을 target으로 변환할 수 있는지 return 하도록 solution 함수를 작성해주세요.
#### 
#### 제한사항
#### 각 단어는 알파벳 소문자로만 이루어져 있습니다.
#### 각 단어의 길이는 3 이상 10 이하이며 모든 단어의 길이는 같습니다.
#### words에는 3개 이상 50개 이하의 단어가 있으며 중복되는 단어는 없습니다.
#### begin과 target은 같지 않습니다.
#### 변환할 수 없는 경우에는 0를 return 합니다.
#### 입출력 예
#### begin	target	words	return
#### "hit"	"cog"	["hot", "dot", "dog", "lot", "log", "cog"]	4
#### "hit"	"cog"	["hot", "dot", "dog", "lot", "log"]	0
#### 입출력 예 설명
#### 예제 #1
#### 문제에 나온 예와 같습니다.
#### 
#### 예제 #2
#### target인 "cog"는 words 안에 없기 때문에 변환할 수 없습니다.
#### 
#### https://programmers.co.kr/learn/courses/30/lessons/43162
#### 
#### 출처: 프로그래머스 코딩 테스트 연습, https://programmers.co.kr/learn/challenges

In [35]:
import numpy as np
def genConvMap(words):
    nWordsLen = len(words)
    map = np.zeros((nWordsLen,nWordsLen), dtype=int)
    for i in range(nWordsLen-1):
        for j in range(i+1, nWordsLen):
            set1 = set(words[i])
            set2 = set(words[j])
            diffSet1 = set1 - set2
            diffSet2 = set2 - set1
            if(len(diffSet1) == len(diffSet2) == 1):
                map[i][j] = map[j][i] = 1
    return map

In [36]:
def CalcConvCnt(idxCurrent, idxTarget, map):
    if(idxCurrent == idxTarget):
        return 1
    else:
        cnt = 0
        for num in map[idxCurrent]:
            if num==1 :
                # 이미 지나온 케이스의 경우 2로 변경
                # cnt 계산법 변경 필요
                cnt += CalcConvCnt(idxCurrent, idxTarget, map)
        return cnt

In [40]:
def solution(begin, target, words):
    if target not in words:
        return 0
    words.append(begin)
    idxCurrent = len(words)-1
    idxTarget = words.index(target)
    map = genConvMap(words)
    print(map)
    return CalcConvCnt(idxCurrent, idxTarget, map)

In [41]:
print(solution("hit", "cog", ["hot", "dot", "dog", "lot", "log", "cog"]))  #4
print(solution("hit", "cog", ["hot", "dot", "dog", "lot", "log"]))         #0

[[0 1 0 1 0 0 1]
 [1 0 1 1 0 0 0]
 [0 1 0 0 1 1 0]
 [1 1 0 0 1 0 0]
 [0 0 1 1 0 1 0]
 [0 0 1 0 1 0 0]
 [1 0 0 0 0 0 0]]
1
0


In [14]:
str1 = 'asd'
str2 = 'asc'

set1 = set(str1)
set2 = set(str2)

diffSet1 = set1 - set2
diffSet2 = set2 - set1

if(len(diffSet1) == len(diffSet2) == 1):
    print(1)

1
